return {
  ["acid-splash-fire-spitter-behemoth"] = require("___KHAOSDATA___.prototypes.data-raw.fire.acid-splash-fire-spitter-behemoth"),
  ["acid-splash-fire-spitter-big"] = require("___KHAOSDATA___.prototypes.data-raw.fire.acid-splash-fire-spitter-big"),
  ["acid-splash-fire-spitter-medium"] = require("___KHAOSDATA___.prototypes.data-raw.fire.acid-splash-fire-spitter-medium"),
  ["acid-splash-fire-spitter-small"] = require("___KHAOSDATA___.prototypes.data-raw.fire.acid-splash-fire-spitter-small"),
  ["acid-splash-fire-worm-behemoth"] = require("___KHAOSDATA___.prototypes.data-raw.fire.acid-splash-fire-worm-behemoth"),
  ["acid-splash-fire-worm-big"] = require("___KHAOSDATA___.prototypes.data-raw.fire.acid-splash-fire-worm-big"),
  ["acid-splash-fire-worm-medium"] = require("___KHAOSDATA___.prototypes.data-raw.fire.acid-splash-fire-worm-medium"),
  ["acid-splash-fire-worm-small"] = require("___KHAOSDATA___.prototypes.data-raw.fire.acid-splash-fire-worm-small"),
  ["crash-site-fire-flame"] = require("___KHAOSDATA___.prototypes.data-raw.fire.crash-site-fire-flame"),
  ["fire-flame"] = require("___KHAOSDATA___.prototypes.data-raw.fire.fire-flame"),
  ["fire-flame-on-tree"] = require("___KHAOSDATA___.prototypes.data-raw.fire.fire-flame-on-tree"),
  ["sut-smokestack"] = require("___KHAOSDATA___.prototypes.data-raw.fire.sut-smokestack"),
  ["sut-smokestack-weak"] = require("___KHAOSDATA___.prototypes.data-raw.fire.sut-smokestack-weak"),
}
