return {
  ["artillery-wagon"] = require("___KHAOSDATA___.prototypes.data-raw.item-with-entity-data.artillery-wagon"),
  ["car"] = require("___KHAOSDATA___.prototypes.data-raw.item-with-entity-data.car"),
  ["cargo-wagon"] = require("___KHAOSDATA___.prototypes.data-raw.item-with-entity-data.cargo-wagon"),
  ["crawdad"] = require("___KHAOSDATA___.prototypes.data-raw.item-with-entity-data.crawdad"),
  ["dingrido"] = require("___KHAOSDATA___.prototypes.data-raw.item-with-entity-data.dingrido"),
  ["fluid-wagon"] = require("___KHAOSDATA___.prototypes.data-raw.item-with-entity-data.fluid-wagon"),
  ["ht-locomotive"] = require("___KHAOSDATA___.prototypes.data-raw.item-with-entity-data.ht-locomotive"),
  ["locomotive"] = require("___KHAOSDATA___.prototypes.data-raw.item-with-entity-data.locomotive"),
  ["mk02-locomotive"] = require("___KHAOSDATA___.prototypes.data-raw.item-with-entity-data.mk02-locomotive"),
  ["mk04-locomotive"] = require("___KHAOSDATA___.prototypes.data-raw.item-with-entity-data.mk04-locomotive"),
  ["phadaisus"] = require("___KHAOSDATA___.prototypes.data-raw.item-with-entity-data.phadaisus"),
  ["spidertron"] = require("___KHAOSDATA___.prototypes.data-raw.item-with-entity-data.spidertron"),
  ["tank"] = require("___KHAOSDATA___.prototypes.data-raw.item-with-entity-data.tank"),
}
