return {
  ["artillery-shell"] = require("___KHAOSDATA___.prototypes.data-raw.ammo.artillery-shell"),
  ["atomic-bomb"] = require("___KHAOSDATA___.prototypes.data-raw.ammo.atomic-bomb"),
  ["cannon-shell"] = require("___KHAOSDATA___.prototypes.data-raw.ammo.cannon-shell"),
  ["dragon-breath-ammo"] = require("___KHAOSDATA___.prototypes.data-raw.ammo.dragon-breath-ammo"),
  ["explosive-cannon-shell"] = require("___KHAOSDATA___.prototypes.data-raw.ammo.explosive-cannon-shell"),
  ["explosive-rocket"] = require("___KHAOSDATA___.prototypes.data-raw.ammo.explosive-rocket"),
  ["explosive-uranium-cannon-shell"] = require("___KHAOSDATA___.prototypes.data-raw.ammo.explosive-uranium-cannon-shell"),
  ["firearm-magazine"] = require("___KHAOSDATA___.prototypes.data-raw.ammo.firearm-magazine"),
  ["flamethrower-ammo"] = require("___KHAOSDATA___.prototypes.data-raw.ammo.flamethrower-ammo"),
  ["nuclear-artillery-shell"] = require("___KHAOSDATA___.prototypes.data-raw.ammo.nuclear-artillery-shell"),
  ["piercing-rounds-magazine"] = require("___KHAOSDATA___.prototypes.data-raw.ammo.piercing-rounds-magazine"),
  ["piercing-shotgun-shell"] = require("___KHAOSDATA___.prototypes.data-raw.ammo.piercing-shotgun-shell"),
  ["rocket"] = require("___KHAOSDATA___.prototypes.data-raw.ammo.rocket"),
  ["shotgun-shell"] = require("___KHAOSDATA___.prototypes.data-raw.ammo.shotgun-shell"),
  ["uranium-cannon-shell"] = require("___KHAOSDATA___.prototypes.data-raw.ammo.uranium-cannon-shell"),
  ["uranium-rounds-magazine"] = require("___KHAOSDATA___.prototypes.data-raw.ammo.uranium-rounds-magazine"),
}
