return {
  ["auog"] = require("___KHAOSDATA___.prototypes.data-raw.fuel-category.auog"),
  ["bio-container"] = require("___KHAOSDATA___.prototypes.data-raw.fuel-category.bio-container"),
  ["bio-reactor-1"] = require("___KHAOSDATA___.prototypes.data-raw.fuel-category.bio-reactor-1"),
  ["bio-reactor-2"] = require("___KHAOSDATA___.prototypes.data-raw.fuel-category.bio-reactor-2"),
  ["bio-reactor-3"] = require("___KHAOSDATA___.prototypes.data-raw.fuel-category.bio-reactor-3"),
  ["biomass"] = require("___KHAOSDATA___.prototypes.data-raw.fuel-category.biomass"),
  ["chemical"] = require("___KHAOSDATA___.prototypes.data-raw.fuel-category.chemical"),
  ["control-rod"] = require("___KHAOSDATA___.prototypes.data-raw.fuel-category.control-rod"),
  ["dingrit-food"] = require("___KHAOSDATA___.prototypes.data-raw.fuel-category.dingrit-food"),
  ["dingrits"] = require("___KHAOSDATA___.prototypes.data-raw.fuel-category.dingrits"),
  ["drill"] = require("___KHAOSDATA___.prototypes.data-raw.fuel-category.drill"),
  ["fish"] = require("___KHAOSDATA___.prototypes.data-raw.fuel-category.fish"),
  ["fuelrod"] = require("___KHAOSDATA___.prototypes.data-raw.fuel-category.fuelrod"),
  ["gastrocapacitor"] = require("___KHAOSDATA___.prototypes.data-raw.fuel-category.gastrocapacitor"),
  ["jerry"] = require("___KHAOSDATA___.prototypes.data-raw.fuel-category.jerry"),
  ["mega-drill-head"] = require("___KHAOSDATA___.prototypes.data-raw.fuel-category.mega-drill-head"),
  ["nexelit"] = require("___KHAOSDATA___.prototypes.data-raw.fuel-category.nexelit"),
  ["nuclear"] = require("___KHAOSDATA___.prototypes.data-raw.fuel-category.nuclear"),
  ["nuke"] = require("___KHAOSDATA___.prototypes.data-raw.fuel-category.nuke"),
  ["personal-fusion-cell"] = require("___KHAOSDATA___.prototypes.data-raw.fuel-category.personal-fusion-cell"),
  ["phadai-food"] = require("___KHAOSDATA___.prototypes.data-raw.fuel-category.phadai-food"),
  ["quantum"] = require("___KHAOSDATA___.prototypes.data-raw.fuel-category.quantum"),
  ["simik"] = require("___KHAOSDATA___.prototypes.data-raw.fuel-category.simik"),
}
