return {
  ["car"] = require("___KHAOSDATA___.prototypes.data-raw.collision-layer.car"),
  ["cliff"] = require("___KHAOSDATA___.prototypes.data-raw.collision-layer.cliff"),
  ["doodad"] = require("___KHAOSDATA___.prototypes.data-raw.collision-layer.doodad"),
  ["elevated_rail"] = require("___KHAOSDATA___.prototypes.data-raw.collision-layer.elevated_rail"),
  ["elevated_train"] = require("___KHAOSDATA___.prototypes.data-raw.collision-layer.elevated_train"),
  ["empty_space"] = require("___KHAOSDATA___.prototypes.data-raw.collision-layer.empty_space"),
  ["floor"] = require("___KHAOSDATA___.prototypes.data-raw.collision-layer.floor"),
  ["ghost"] = require("___KHAOSDATA___.prototypes.data-raw.collision-layer.ghost"),
  ["ground_tile"] = require("___KHAOSDATA___.prototypes.data-raw.collision-layer.ground_tile"),
  ["is_lower_object"] = require("___KHAOSDATA___.prototypes.data-raw.collision-layer.is_lower_object"),
  ["is_object"] = require("___KHAOSDATA___.prototypes.data-raw.collision-layer.is_object"),
  ["item"] = require("___KHAOSDATA___.prototypes.data-raw.collision-layer.item"),
  ["lava_tile"] = require("___KHAOSDATA___.prototypes.data-raw.collision-layer.lava_tile"),
  ["meltable"] = require("___KHAOSDATA___.prototypes.data-raw.collision-layer.meltable"),
  ["object"] = require("___KHAOSDATA___.prototypes.data-raw.collision-layer.object"),
  ["out_of_map"] = require("___KHAOSDATA___.prototypes.data-raw.collision-layer.out_of_map"),
  ["player"] = require("___KHAOSDATA___.prototypes.data-raw.collision-layer.player"),
  ["rail"] = require("___KHAOSDATA___.prototypes.data-raw.collision-layer.rail"),
  ["rail_support"] = require("___KHAOSDATA___.prototypes.data-raw.collision-layer.rail_support"),
  ["resource"] = require("___KHAOSDATA___.prototypes.data-raw.collision-layer.resource"),
  ["train"] = require("___KHAOSDATA___.prototypes.data-raw.collision-layer.train"),
  ["transport_belt"] = require("___KHAOSDATA___.prototypes.data-raw.collision-layer.transport_belt"),
  ["trigger_target"] = require("___KHAOSDATA___.prototypes.data-raw.collision-layer.trigger_target"),
  ["water_tile"] = require("___KHAOSDATA___.prototypes.data-raw.collision-layer.water_tile"),
}
