return {
  ["atomic-bomb-ground-zero-projectile"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.atomic-bomb-ground-zero-projectile"),
  ["atomic-bomb-wave"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.atomic-bomb-wave"),
  ["atomic-bomb-wave-spawns-cluster-nuke-explosion"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.atomic-bomb-wave-spawns-cluster-nuke-explosion"),
  ["atomic-bomb-wave-spawns-fire-smoke-explosion"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.atomic-bomb-wave-spawns-fire-smoke-explosion"),
  ["atomic-bomb-wave-spawns-nuclear-smoke"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.atomic-bomb-wave-spawns-nuclear-smoke"),
  ["atomic-bomb-wave-spawns-nuke-shockwave-explosion"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.atomic-bomb-wave-spawns-nuke-shockwave-explosion"),
  ["atomic-rocket"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.atomic-rocket"),
  ["blue-laser"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.blue-laser"),
  ["cannon-projectile"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.cannon-projectile"),
  ["cliff-explosives"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.cliff-explosives"),
  ["cluster-grenade"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.cluster-grenade"),
  ["defender-capsule"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.defender-capsule"),
  ["destroyer-capsule"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.destroyer-capsule"),
  ["distractor-capsule"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.distractor-capsule"),
  ["explosive-cannon-projectile"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.explosive-cannon-projectile"),
  ["explosive-rocket"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.explosive-rocket"),
  ["explosive-uranium-cannon-projectile"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.explosive-uranium-cannon-projectile"),
  ["grenade"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.grenade"),
  ["laser"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.laser"),
  ["piercing-shotgun-pellet"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.piercing-shotgun-pellet"),
  ["poison-capsule"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.poison-capsule"),
  ["rocket"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.rocket"),
  ["shotgun-pellet"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.shotgun-pellet"),
  ["slowdown-capsule"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.slowdown-capsule"),
  ["uranium-cannon-projectile"] = require("___KHAOSDATA___.prototypes.data-raw.projectile.uranium-cannon-projectile"),
}
