return {
  ["barrel-machine-mk01"] = require("___KHAOSDATA___.prototypes.data-raw.furnace.barrel-machine-mk01"),
  ["co2-absorber"] = require("___KHAOSDATA___.prototypes.data-raw.furnace.co2-absorber"),
  ["compost-plant-mk01"] = require("___KHAOSDATA___.prototypes.data-raw.furnace.compost-plant-mk01"),
  ["compost-plant-mk01-turd"] = require("___KHAOSDATA___.prototypes.data-raw.furnace.compost-plant-mk01-turd"),
  ["compost-plant-mk02"] = require("___KHAOSDATA___.prototypes.data-raw.furnace.compost-plant-mk02"),
  ["compost-plant-mk02-turd"] = require("___KHAOSDATA___.prototypes.data-raw.furnace.compost-plant-mk02-turd"),
  ["compost-plant-mk03"] = require("___KHAOSDATA___.prototypes.data-raw.furnace.compost-plant-mk03"),
  ["compost-plant-mk03-turd"] = require("___KHAOSDATA___.prototypes.data-raw.furnace.compost-plant-mk03-turd"),
  ["compost-plant-mk04"] = require("___KHAOSDATA___.prototypes.data-raw.furnace.compost-plant-mk04"),
  ["compost-plant-mk04-turd"] = require("___KHAOSDATA___.prototypes.data-raw.furnace.compost-plant-mk04-turd"),
  ["electric-furnace"] = require("___KHAOSDATA___.prototypes.data-raw.furnace.electric-furnace"),
  ["provider-tank"] = require("___KHAOSDATA___.prototypes.data-raw.furnace.provider-tank"),
  ["py-burner"] = require("___KHAOSDATA___.prototypes.data-raw.furnace.py-burner"),
  ["py-gas-vent"] = require("___KHAOSDATA___.prototypes.data-raw.furnace.py-gas-vent"),
  ["py-sinkhole"] = require("___KHAOSDATA___.prototypes.data-raw.furnace.py-sinkhole"),
  ["requester-tank"] = require("___KHAOSDATA___.prototypes.data-raw.furnace.requester-tank"),
  ["steel-furnace"] = require("___KHAOSDATA___.prototypes.data-raw.furnace.steel-furnace"),
  ["stone-furnace"] = require("___KHAOSDATA___.prototypes.data-raw.furnace.stone-furnace"),
}
