return {
  expression = "lerp(starting_main_blend, -1, enemies_water_knockout)",
  local_expressions = {
    enemies_water_knockout = "clamp(max(gleba_starting_enemies_safe, gleba_starting_enemies) * 2, 0, 1)",
    high_frequency = "multioctave_noise{x = x, y = y, persistence = 0.7, seed0 = map_seed, seed1 = 1, octaves = 3, input_scale = 1/18}",
    peaks = "multioctave_noise{x = x + gleba_wobble_x * 10, y = y + gleba_wobble_y * 10, persistence = 0.7, seed0 = map_seed, seed1 = 1000000, octaves = 3, input_scale = 1/60*slider_rescale(gleba_water_frequency, 3)} + ridges",
    peaks_terrace = "terrace{value = min(150, -25 + peaks * 250), offset = 40, width = 20, strength = 0.2}",
    ridge_terrace = "terrace{value = min(80, 110 + ridges * 500), offset = 40, width = 20, strength = 0.2}",
    ridges = "max(-gleba_tri_ridge * (0.6 + var('control:gleba_water:size') / 3), starting_bridges - 0.8) * 2.4 + 0.2 * ridges_small_noise",
    ridges_small_noise = "abs(multioctave_noise{x = x, y = y, persistence = 0.7, seed0 = map_seed, seed1 = 1000000, octaves = 3, input_scale = 1/60})",
    rockpool_elevation = "lerp(lerp(20, 80, gleba_rockpools < 0.3), 250, gleba_rockpools < 0.01)",
    spiral_angle = "gleba_starting_angle - gleba_starting_direction * (distance / gleba_starting_area_multiplier / 16 - 15)",
    spiral_angle_b = "gleba_starting_angle + gleba_starting_direction * (distance / gleba_starting_area_multiplier / 16 - 15)",
    starting_area = "max(-30 * clamp(starting_lakes * 2, 0, 1), 5 * min(gleba_starting_lowlands * 2, 1), 130 * min(starting_highlands * 2, 1), 80 * min(starting_midlands * 2, 1), 70 * min((starting_bridges - 0.5) * 3, 1)) + 6 * ridges_small_noise",
    starting_bridge = "min(1 - abs(starting_rotated_x / gleba_starting_area_multiplier - gleba_starting_direction * sin(starting_rotated_y / 64 / gleba_starting_area_multiplier) * 64 * gleba_starting_area_multiplier) / 110, 2 - distance / gleba_starting_area_multiplier / 700)",
    starting_bridge_b = "min(1 - abs(starting_rotated_b_x / gleba_starting_area_multiplier - gleba_starting_direction * sin(starting_rotated_b_y / 64 / gleba_starting_area_multiplier) * 64 * gleba_starting_area_multiplier) / 110, 2 - distance / gleba_starting_area_multiplier / 700)",
    starting_bridges = "max(starting_bridge, starting_bridge_b)",
    starting_highland_main = "starting_spot_at_angle{ angle = gleba_starting_angle + 95 * gleba_starting_direction,distance = 100 * gleba_starting_area_multiplier,radius = 130 * gleba_starting_area_multiplier,x_distortion = gleba_wobble_x * 15,y_distortion = gleba_wobble_x * 15}",
    starting_highland_small = "starting_spot_at_angle{angle = gleba_starting_angle + 40 * gleba_starting_direction,distance = 130 * gleba_starting_area_multiplier,radius = 65 * gleba_starting_area_multiplier,x_distortion = gleba_wobble_x * 15,y_distortion = gleba_wobble_x * 15}",
    starting_highlands = "max(starting_highland_main, starting_highland_small)",
    starting_lakes = "max(starting_stone_lake, starting_opposite_lake, starting_opposite_small_lake)",
    starting_main_blend = "min(rockpool_elevation, lerp(terraces_combined, starting_area, clamp(1.7 - (distance / gleba_starting_area_multiplier / 500), 0, 1))) + 3 * (0.5 - abs(high_frequency))",
    starting_midland_copper = "starting_spot_at_angle{angle = gleba_starting_angle + 340 * gleba_starting_direction,distance = 100 * gleba_starting_area_multiplier,radius = 80 * gleba_starting_area_multiplier,x_distortion = gleba_wobble_x * 15,y_distortion = gleba_wobble_x * 15}",
    starting_midland_iron = "starting_spot_at_angle{angle = gleba_starting_angle + 180 * gleba_starting_direction,distance = 120 * gleba_starting_area_multiplier,radius = 130 * gleba_starting_area_multiplier,x_distortion = gleba_wobble_x * 15,y_distortion = gleba_wobble_x * 15}",
    starting_midland_landing = "starting_spot_at_angle{ angle = gleba_starting_angle + 265 * gleba_starting_direction,distance = 10 * gleba_starting_area_multiplier,radius = 80 * gleba_starting_area_multiplier,x_distortion = gleba_wobble_x * 15,y_distortion = gleba_wobble_x * 15}",
    starting_midlands = "max(starting_midland_landing, starting_midland_iron, starting_midland_copper)",
    starting_opposite_lake = "starting_spot_at_angle{ angle = gleba_starting_angle + 270 * gleba_starting_direction,distance = 500 * gleba_starting_area_multiplier,radius = 450 * gleba_starting_area_multiplier,x_distortion = gleba_wobble_x * 15,y_distortion = gleba_wobble_x * 15}",
    starting_opposite_small_lake = "starting_spot_at_angle{ angle = gleba_starting_angle + 265 * gleba_starting_direction,distance = 50 * gleba_starting_area_multiplier,radius = 50 * gleba_starting_area_multiplier,x_distortion = gleba_wobble_x * 15,y_distortion = gleba_wobble_x * 15}",
    starting_rotated_b_x = "rotate_x(x_from_start, y_from_start, spiral_angle_b) + gleba_wobble_x * 10",
    starting_rotated_b_y = "rotate_y(x_from_start, y_from_start, spiral_angle_b) + gleba_wobble_y * 10",
    starting_rotated_x = "rotate_x(x_from_start, y_from_start, spiral_angle) + gleba_wobble_x * 10",
    starting_rotated_y = "rotate_y(x_from_start, y_from_start, spiral_angle) + gleba_wobble_y * 10",
    starting_stone_lake = "starting_spot_at_angle{angle = gleba_starting_angle + 90 * gleba_starting_direction,distance = 500 * gleba_starting_area_multiplier,radius = 350 * gleba_starting_area_multiplier,x_distortion = gleba_wobble_x * 15,y_distortion = gleba_wobble_x * 15}",
    terraces_combined = "max(ridge_terrace, peaks_terrace, 25 + 22 * ridges)"
  },
  name = "gleba_elevation_common",
  type = "noise-expression"
}
