return {
  ["acid-sticker-behemoth"] = require("___KHAOSDATA___.prototypes.data-raw.sticker.acid-sticker-behemoth"),
  ["acid-sticker-big"] = require("___KHAOSDATA___.prototypes.data-raw.sticker.acid-sticker-big"),
  ["acid-sticker-medium"] = require("___KHAOSDATA___.prototypes.data-raw.sticker.acid-sticker-medium"),
  ["acid-sticker-small"] = require("___KHAOSDATA___.prototypes.data-raw.sticker.acid-sticker-small"),
  ["big-acid-sticker-stomper"] = require("___KHAOSDATA___.prototypes.data-raw.sticker.big-acid-sticker-stomper"),
  ["bioflux-speed-regen-sticker"] = require("___KHAOSDATA___.prototypes.data-raw.sticker.bioflux-speed-regen-sticker"),
  ["bioflux-speed-regen-sticker-behind"] = require("___KHAOSDATA___.prototypes.data-raw.sticker.bioflux-speed-regen-sticker-behind"),
  ["demolisher-ash-sticker"] = require("___KHAOSDATA___.prototypes.data-raw.sticker.demolisher-ash-sticker"),
  ["electric-mini-stun"] = require("___KHAOSDATA___.prototypes.data-raw.sticker.electric-mini-stun"),
  ["fire-sticker"] = require("___KHAOSDATA___.prototypes.data-raw.sticker.fire-sticker"),
  ["jellynut-speed-sticker"] = require("___KHAOSDATA___.prototypes.data-raw.sticker.jellynut-speed-sticker"),
  ["jellynut-speed-sticker-behind"] = require("___KHAOSDATA___.prototypes.data-raw.sticker.jellynut-speed-sticker-behind"),
  ["medium-acid-sticker-stomper"] = require("___KHAOSDATA___.prototypes.data-raw.sticker.medium-acid-sticker-stomper"),
  ["shotgun-impact-sticker"] = require("___KHAOSDATA___.prototypes.data-raw.sticker.shotgun-impact-sticker"),
  ["slowdown-sticker"] = require("___KHAOSDATA___.prototypes.data-raw.sticker.slowdown-sticker"),
  ["small-acid-sticker-stomper"] = require("___KHAOSDATA___.prototypes.data-raw.sticker.small-acid-sticker-stomper"),
  ["strafer-sticker"] = require("___KHAOSDATA___.prototypes.data-raw.sticker.strafer-sticker"),
  ["stun-sticker"] = require("___KHAOSDATA___.prototypes.data-raw.sticker.stun-sticker"),
  ["tesla-turret-slow"] = require("___KHAOSDATA___.prototypes.data-raw.sticker.tesla-turret-slow"),
  ["tesla-turret-stun"] = require("___KHAOSDATA___.prototypes.data-raw.sticker.tesla-turret-stun"),
  ["yumako-regen-sticker"] = require("___KHAOSDATA___.prototypes.data-raw.sticker.yumako-regen-sticker"),
  ["yumako-regen-sticker-behind"] = require("___KHAOSDATA___.prototypes.data-raw.sticker.yumako-regen-sticker-behind"),
}
