return {
  ["advanced-crafting"] = require("___KHAOSDATA___.prototypes.data-raw.recipe-category.advanced-crafting"),
  ["captive-spawner-process"] = require("___KHAOSDATA___.prototypes.data-raw.recipe-category.captive-spawner-process"),
  ["centrifuging"] = require("___KHAOSDATA___.prototypes.data-raw.recipe-category.centrifuging"),
  ["chemistry"] = require("___KHAOSDATA___.prototypes.data-raw.recipe-category.chemistry"),
  ["crafting"] = require("___KHAOSDATA___.prototypes.data-raw.recipe-category.crafting"),
  ["crafting-with-fluid"] = require("___KHAOSDATA___.prototypes.data-raw.recipe-category.crafting-with-fluid"),
  ["crushing"] = require("___KHAOSDATA___.prototypes.data-raw.recipe-category.crushing"),
  ["cryogenics"] = require("___KHAOSDATA___.prototypes.data-raw.recipe-category.cryogenics"),
  ["electromagnetics"] = require("___KHAOSDATA___.prototypes.data-raw.recipe-category.electromagnetics"),
  ["hand-crafting"] = require("___KHAOSDATA___.prototypes.data-raw.recipe-category.hand-crafting"),
  ["metallurgy"] = require("___KHAOSDATA___.prototypes.data-raw.recipe-category.metallurgy"),
  ["oil-processing"] = require("___KHAOSDATA___.prototypes.data-raw.recipe-category.oil-processing"),
  ["organic"] = require("___KHAOSDATA___.prototypes.data-raw.recipe-category.organic"),
  ["parameters"] = require("___KHAOSDATA___.prototypes.data-raw.recipe-category.parameters"),
  ["recycling"] = require("___KHAOSDATA___.prototypes.data-raw.recipe-category.recycling"),
  ["rocket-building"] = require("___KHAOSDATA___.prototypes.data-raw.recipe-category.rocket-building"),
  ["smelting"] = require("___KHAOSDATA___.prototypes.data-raw.recipe-category.smelting"),
}
