return {
  localised_description = {
    "?",
    {
      "",
      {
        "resource-category-description.borax"
      },
      "\n",
      {
        "",
        {
          "?",
          {
            "",
            "",
            {
              "?",
              {
                "autoplace-control-names.borax"
              },
              {
                "",
                "[img=entity.borax]",
                {
                  "entity-name.borax"
                }
              }
            }
          }
        },
        {
          "?",
          {
            "",
            ", ",
            {
              "?",
              {
                "autoplace-control-names.ore-quartz"
              },
              {
                "",
                "[img=entity.ore-quartz]",
                {
                  "entity-name.ore-quartz"
                }
              }
            }
          }
        }
      }
    },
    {
      "",
      {
        "?",
        {
          "",
          "",
          {
            "?",
            {
              "autoplace-control-names.borax"
            },
            {
              "",
              "[img=entity.borax]",
              {
                "entity-name.borax"
              }
            }
          }
        }
      },
      {
        "?",
        {
          "",
          ", ",
          {
            "?",
            {
              "autoplace-control-names.ore-quartz"
            },
            {
              "",
              "[img=entity.ore-quartz]",
              {
                "entity-name.ore-quartz"
              }
            }
          }
        }
      }
    }
  },
  name = "borax",
  type = "resource-category"
}
