return {
  localised_description = {
    "?",
    {
      "",
      {
        "resource-category-description.natural-gas"
      },
      "\n",
      {
        "",
        {
          "?",
          {
            "",
            "",
            {
              "?",
              {
                "autoplace-control-names.natural-gas-mk01"
              },
              {
                "",
                "[img=entity.natural-gas-mk01]",
                {
                  "entity-name.natural-gas-mk01"
                }
              }
            }
          }
        },
        {
          "?",
          {
            "",
            ", ",
            {
              "?",
              {
                "autoplace-control-names.natural-gas-mk02"
              },
              {
                "",
                "[img=entity.natural-gas-mk02]",
                {
                  "entity-name.natural-gas-mk02"
                }
              }
            }
          }
        },
        {
          "?",
          {
            "",
            ", ",
            {
              "?",
              {
                "autoplace-control-names.natural-gas-mk03"
              },
              {
                "",
                "[img=entity.natural-gas-mk03]",
                {
                  "entity-name.natural-gas-mk03"
                }
              }
            }
          }
        },
        {
          "?",
          {
            "",
            ", ",
            {
              "?",
              {
                "autoplace-control-names.natural-gas-mk04"
              },
              {
                "",
                "[img=entity.natural-gas-mk04]",
                {
                  "entity-name.natural-gas-mk04"
                }
              }
            }
          }
        }
      }
    },
    {
      "",
      {
        "?",
        {
          "",
          "",
          {
            "?",
            {
              "autoplace-control-names.natural-gas-mk01"
            },
            {
              "",
              "[img=entity.natural-gas-mk01]",
              {
                "entity-name.natural-gas-mk01"
              }
            }
          }
        }
      },
      {
        "?",
        {
          "",
          ", ",
          {
            "?",
            {
              "autoplace-control-names.natural-gas-mk02"
            },
            {
              "",
              "[img=entity.natural-gas-mk02]",
              {
                "entity-name.natural-gas-mk02"
              }
            }
          }
        }
      },
      {
        "?",
        {
          "",
          ", ",
          {
            "?",
            {
              "autoplace-control-names.natural-gas-mk03"
            },
            {
              "",
              "[img=entity.natural-gas-mk03]",
              {
                "entity-name.natural-gas-mk03"
              }
            }
          }
        }
      },
      {
        "?",
        {
          "",
          ", ",
          {
            "?",
            {
              "autoplace-control-names.natural-gas-mk04"
            },
            {
              "",
              "[img=entity.natural-gas-mk04]",
              {
                "entity-name.natural-gas-mk04"
              }
            }
          }
        }
      }
    }
  },
  name = "natural-gas",
  type = "resource-category"
}
