return {
  ["compi"] = require("___KHAOSDATA___.prototypes.data-raw.font.compi"),
  ["count-font"] = require("___KHAOSDATA___.prototypes.data-raw.font.count-font"),
  ["default"] = require("___KHAOSDATA___.prototypes.data-raw.font.default"),
  ["default-bold"] = require("___KHAOSDATA___.prototypes.data-raw.font.default-bold"),
  ["default-dialog-button"] = require("___KHAOSDATA___.prototypes.data-raw.font.default-dialog-button"),
  ["default-dropdown"] = require("___KHAOSDATA___.prototypes.data-raw.font.default-dropdown"),
  ["default-game"] = require("___KHAOSDATA___.prototypes.data-raw.font.default-game"),
  ["default-large"] = require("___KHAOSDATA___.prototypes.data-raw.font.default-large"),
  ["default-large-bold"] = require("___KHAOSDATA___.prototypes.data-raw.font.default-large-bold"),
  ["default-large-semibold"] = require("___KHAOSDATA___.prototypes.data-raw.font.default-large-semibold"),
  ["default-listbox"] = require("___KHAOSDATA___.prototypes.data-raw.font.default-listbox"),
  ["default-semibold"] = require("___KHAOSDATA___.prototypes.data-raw.font.default-semibold"),
  ["default-small"] = require("___KHAOSDATA___.prototypes.data-raw.font.default-small"),
  ["default-small-bold"] = require("___KHAOSDATA___.prototypes.data-raw.font.default-small-bold"),
  ["default-small-semibold"] = require("___KHAOSDATA___.prototypes.data-raw.font.default-small-semibold"),
  ["default-tiny-bold"] = require("___KHAOSDATA___.prototypes.data-raw.font.default-tiny-bold"),
  ["heading-1"] = require("___KHAOSDATA___.prototypes.data-raw.font.heading-1"),
  ["heading-2"] = require("___KHAOSDATA___.prototypes.data-raw.font.heading-2"),
  ["locale-pick"] = require("___KHAOSDATA___.prototypes.data-raw.font.locale-pick"),
  ["scenario-message-dialog"] = require("___KHAOSDATA___.prototypes.data-raw.font.scenario-message-dialog"),
  ["technology-slot-level-font"] = require("___KHAOSDATA___.prototypes.data-raw.font.technology-slot-level-font"),
  ["var"] = require("___KHAOSDATA___.prototypes.data-raw.font.var"),
}
