return {
  ["active-provider-chest"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.active-provider-chest"),
  ["buffer-chest"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.buffer-chest"),
  ["passive-provider-chest"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.passive-provider-chest"),
  ["py-deposit-active-provider"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.py-deposit-active-provider"),
  ["py-deposit-buffer"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.py-deposit-buffer"),
  ["py-deposit-passive-provider"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.py-deposit-passive-provider"),
  ["py-deposit-requester"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.py-deposit-requester"),
  ["py-deposit-storage"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.py-deposit-storage"),
  ["py-shed-active-provider"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.py-shed-active-provider"),
  ["py-shed-buffer"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.py-shed-buffer"),
  ["py-shed-passive-provider"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.py-shed-passive-provider"),
  ["py-shed-requester"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.py-shed-requester"),
  ["py-shed-storage"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.py-shed-storage"),
  ["py-storehouse-active-provider"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.py-storehouse-active-provider"),
  ["py-storehouse-buffer"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.py-storehouse-buffer"),
  ["py-storehouse-passive-provider"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.py-storehouse-passive-provider"),
  ["py-storehouse-requester"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.py-storehouse-requester"),
  ["py-storehouse-storage"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.py-storehouse-storage"),
  ["py-warehouse-active-provider"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.py-warehouse-active-provider"),
  ["py-warehouse-buffer"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.py-warehouse-buffer"),
  ["py-warehouse-passive-provider"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.py-warehouse-passive-provider"),
  ["py-warehouse-requester"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.py-warehouse-requester"),
  ["py-warehouse-storage"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.py-warehouse-storage"),
  ["requester-chest"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.requester-chest"),
  ["storage-chest"] = require("___KHAOSDATA___.prototypes.data-raw.logistic-container.storage-chest"),
}
