return {
  ["artillery-smoke"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.artillery-smoke"),
  ["car-smoke"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.car-smoke"),
  ["fire-smoke"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.fire-smoke"),
  ["fire-smoke-on-adding-fuel"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.fire-smoke-on-adding-fuel"),
  ["fire-smoke-without-glow"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.fire-smoke-without-glow"),
  ["light-smoke"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.light-smoke"),
  ["nuclear-smoke"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.nuclear-smoke"),
  ["poison-capsule-particle-smoke"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.poison-capsule-particle-smoke"),
  ["poison-capsule-smoke"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.poison-capsule-smoke"),
  ["small-dust-particle-smoke"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.small-dust-particle-smoke"),
  ["small-dusty-explosion-smoke"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.small-dusty-explosion-smoke"),
  ["smoke"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.smoke"),
  ["smoke-building"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.smoke-building"),
  ["smoke-explosion-lower-particle-small"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.smoke-explosion-lower-particle-small"),
  ["smoke-explosion-particle"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.smoke-explosion-particle"),
  ["smoke-explosion-particle-small"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.smoke-explosion-particle-small"),
  ["smoke-explosion-particle-stone-small"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.smoke-explosion-particle-stone-small"),
  ["smoke-explosion-particle-tiny"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.smoke-explosion-particle-tiny"),
  ["smoke-fast"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.smoke-fast"),
  ["smoke-train-stop"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.smoke-train-stop"),
  ["soft-fire-smoke"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.soft-fire-smoke"),
  ["sut-smoke"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.sut-smoke"),
  ["tank-smoke"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.tank-smoke"),
  ["train-smoke"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.train-smoke"),
  ["turbine-smoke"] = require("___KHAOSDATA___.prototypes.data-raw.trivial-smoke.turbine-smoke"),
}
