return {
  ["crude-oil"] = require("___KHAOSDATA___.prototypes.data-raw.fluid.crude-oil"),
  ["fluid-unknown"] = require("___KHAOSDATA___.prototypes.data-raw.fluid.fluid-unknown"),
  ["heavy-oil"] = require("___KHAOSDATA___.prototypes.data-raw.fluid.heavy-oil"),
  ["light-oil"] = require("___KHAOSDATA___.prototypes.data-raw.fluid.light-oil"),
  ["lubricant"] = require("___KHAOSDATA___.prototypes.data-raw.fluid.lubricant"),
  ["parameter-0"] = require("___KHAOSDATA___.prototypes.data-raw.fluid.parameter-0"),
  ["parameter-1"] = require("___KHAOSDATA___.prototypes.data-raw.fluid.parameter-1"),
  ["parameter-2"] = require("___KHAOSDATA___.prototypes.data-raw.fluid.parameter-2"),
  ["parameter-3"] = require("___KHAOSDATA___.prototypes.data-raw.fluid.parameter-3"),
  ["parameter-4"] = require("___KHAOSDATA___.prototypes.data-raw.fluid.parameter-4"),
  ["parameter-5"] = require("___KHAOSDATA___.prototypes.data-raw.fluid.parameter-5"),
  ["parameter-6"] = require("___KHAOSDATA___.prototypes.data-raw.fluid.parameter-6"),
  ["parameter-7"] = require("___KHAOSDATA___.prototypes.data-raw.fluid.parameter-7"),
  ["parameter-8"] = require("___KHAOSDATA___.prototypes.data-raw.fluid.parameter-8"),
  ["parameter-9"] = require("___KHAOSDATA___.prototypes.data-raw.fluid.parameter-9"),
  ["petroleum-gas"] = require("___KHAOSDATA___.prototypes.data-raw.fluid.petroleum-gas"),
  ["steam"] = require("___KHAOSDATA___.prototypes.data-raw.fluid.steam"),
  ["sulfuric-acid"] = require("___KHAOSDATA___.prototypes.data-raw.fluid.sulfuric-acid"),
  ["water"] = require("___KHAOSDATA___.prototypes.data-raw.fluid.water"),
}
