return {
  ["coal-processing"] = require("___KHAOSDATA___.prototypes.data-raw.item-group.coal-processing"),
  ["combat"] = require("___KHAOSDATA___.prototypes.data-raw.item-group.combat"),
  ["effects"] = require("___KHAOSDATA___.prototypes.data-raw.item-group.effects"),
  ["enemies"] = require("___KHAOSDATA___.prototypes.data-raw.item-group.enemies"),
  ["environment"] = require("___KHAOSDATA___.prototypes.data-raw.item-group.environment"),
  ["fluids"] = require("___KHAOSDATA___.prototypes.data-raw.item-group.fluids"),
  ["fusion-energy"] = require("___KHAOSDATA___.prototypes.data-raw.item-group.fusion-energy"),
  ["intermediate-products"] = require("___KHAOSDATA___.prototypes.data-raw.item-group.intermediate-products"),
  ["logistics"] = require("___KHAOSDATA___.prototypes.data-raw.item-group.logistics"),
  ["other"] = require("___KHAOSDATA___.prototypes.data-raw.item-group.other"),
  ["production"] = require("___KHAOSDATA___.prototypes.data-raw.item-group.production"),
  ["py-alienlife"] = require("___KHAOSDATA___.prototypes.data-raw.item-group.py-alienlife"),
  ["py-alternativeenergy"] = require("___KHAOSDATA___.prototypes.data-raw.item-group.py-alternativeenergy"),
  ["py-hightech"] = require("___KHAOSDATA___.prototypes.data-raw.item-group.py-hightech"),
  ["py-industry"] = require("___KHAOSDATA___.prototypes.data-raw.item-group.py-industry"),
  ["py-petroleum-handling"] = require("___KHAOSDATA___.prototypes.data-raw.item-group.py-petroleum-handling"),
  ["py-rawores"] = require("___KHAOSDATA___.prototypes.data-raw.item-group.py-rawores"),
  ["signals"] = require("___KHAOSDATA___.prototypes.data-raw.item-group.signals"),
  ["tiles"] = require("___KHAOSDATA___.prototypes.data-raw.item-group.tiles"),
}
