return {
  ["artillery-wagon-cannon"] = require("___KHAOSDATA___.prototypes.data-raw.gun.artillery-wagon-cannon"),
  ["combat-shotgun"] = require("___KHAOSDATA___.prototypes.data-raw.gun.combat-shotgun"),
  ["flamethrower"] = require("___KHAOSDATA___.prototypes.data-raw.gun.flamethrower"),
  ["pistol"] = require("___KHAOSDATA___.prototypes.data-raw.gun.pistol"),
  ["railgun"] = require("___KHAOSDATA___.prototypes.data-raw.gun.railgun"),
  ["rocket-launcher"] = require("___KHAOSDATA___.prototypes.data-raw.gun.rocket-launcher"),
  ["shotgun"] = require("___KHAOSDATA___.prototypes.data-raw.gun.shotgun"),
  ["spidertron-rocket-launcher-1"] = require("___KHAOSDATA___.prototypes.data-raw.gun.spidertron-rocket-launcher-1"),
  ["spidertron-rocket-launcher-2"] = require("___KHAOSDATA___.prototypes.data-raw.gun.spidertron-rocket-launcher-2"),
  ["spidertron-rocket-launcher-3"] = require("___KHAOSDATA___.prototypes.data-raw.gun.spidertron-rocket-launcher-3"),
  ["spidertron-rocket-launcher-4"] = require("___KHAOSDATA___.prototypes.data-raw.gun.spidertron-rocket-launcher-4"),
  ["submachine-gun"] = require("___KHAOSDATA___.prototypes.data-raw.gun.submachine-gun"),
  ["tank-cannon"] = require("___KHAOSDATA___.prototypes.data-raw.gun.tank-cannon"),
  ["tank-flamethrower"] = require("___KHAOSDATA___.prototypes.data-raw.gun.tank-flamethrower"),
  ["tank-machine-gun"] = require("___KHAOSDATA___.prototypes.data-raw.gun.tank-machine-gun"),
  ["teslagun"] = require("___KHAOSDATA___.prototypes.data-raw.gun.teslagun"),
  ["vehicle-machine-gun"] = require("___KHAOSDATA___.prototypes.data-raw.gun.vehicle-machine-gun"),
}
