return {
  ["artillery-shell"] = require("___KHAOSDATA___.prototypes.data-raw.ammo-category.artillery-shell"),
  ["beam"] = require("___KHAOSDATA___.prototypes.data-raw.ammo-category.beam"),
  ["biological"] = require("___KHAOSDATA___.prototypes.data-raw.ammo-category.biological"),
  ["bullet"] = require("___KHAOSDATA___.prototypes.data-raw.ammo-category.bullet"),
  ["cannon-shell"] = require("___KHAOSDATA___.prototypes.data-raw.ammo-category.cannon-shell"),
  ["capsule"] = require("___KHAOSDATA___.prototypes.data-raw.ammo-category.capsule"),
  ["electric"] = require("___KHAOSDATA___.prototypes.data-raw.ammo-category.electric"),
  ["flamethrower"] = require("___KHAOSDATA___.prototypes.data-raw.ammo-category.flamethrower"),
  ["grenade"] = require("___KHAOSDATA___.prototypes.data-raw.ammo-category.grenade"),
  ["landmine"] = require("___KHAOSDATA___.prototypes.data-raw.ammo-category.landmine"),
  ["laser"] = require("___KHAOSDATA___.prototypes.data-raw.ammo-category.laser"),
  ["melee"] = require("___KHAOSDATA___.prototypes.data-raw.ammo-category.melee"),
  ["railgun"] = require("___KHAOSDATA___.prototypes.data-raw.ammo-category.railgun"),
  ["rocket"] = require("___KHAOSDATA___.prototypes.data-raw.ammo-category.rocket"),
  ["seismic"] = require("___KHAOSDATA___.prototypes.data-raw.ammo-category.seismic"),
  ["shotgun-shell"] = require("___KHAOSDATA___.prototypes.data-raw.ammo-category.shotgun-shell"),
  ["tesla"] = require("___KHAOSDATA___.prototypes.data-raw.ammo-category.tesla"),
}
