return {
  ["after-the-crash"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.after-the-crash"),
  ["anomaly"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.anomaly"),
  ["are-we-alone"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.are-we-alone"),
  ["automation"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.automation"),
  ["beyond-factory-outskirts"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.beyond-factory-outskirts"),
  ["censeqs-discrepancy"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.censeqs-discrepancy"),
  ["efficiency-program"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.efficiency-program"),
  ["expansion"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.expansion"),
  ["first-light"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.first-light"),
  ["gathering-horizon"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.gathering-horizon"),
  ["main-menu"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.main-menu"),
  ["pollution"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.pollution"),
  ["research-and-minerals"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.research-and-minerals"),
  ["resource-deficiency"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.resource-deficiency"),
  ["sentient"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.sentient"),
  ["solar-intervention"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.solar-intervention"),
  ["swell-pad"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.swell-pad"),
  ["the-oil-industry"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.the-oil-industry"),
  ["the-right-tools"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.the-right-tools"),
  ["the-search-for-iron"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.the-search-for-iron"),
  ["transmit"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.transmit"),
  ["turbine-dynamics"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.turbine-dynamics"),
  ["world-ambience-3"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.world-ambience-3"),
  ["world-ambience-4"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.world-ambience-4"),
  ["world-ambience-5"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.world-ambience-5"),
  ["world-ambience-6"] = require("___KHAOSDATA___.prototypes.data-raw.ambient-sound.world-ambience-6"),
}
