return {
  ["blue-chest"] = require("___KHAOSDATA___.prototypes.data-raw.container.blue-chest"),
  ["bottomless-chest"] = require("___KHAOSDATA___.prototypes.data-raw.container.bottomless-chest"),
  ["crash-site-chest-1"] = require("___KHAOSDATA___.prototypes.data-raw.container.crash-site-chest-1"),
  ["crash-site-chest-2"] = require("___KHAOSDATA___.prototypes.data-raw.container.crash-site-chest-2"),
  ["crash-site-spaceship"] = require("___KHAOSDATA___.prototypes.data-raw.container.crash-site-spaceship"),
  ["crash-site-spaceship-wreck-big-1"] = require("___KHAOSDATA___.prototypes.data-raw.container.crash-site-spaceship-wreck-big-1"),
  ["crash-site-spaceship-wreck-big-2"] = require("___KHAOSDATA___.prototypes.data-raw.container.crash-site-spaceship-wreck-big-2"),
  ["crash-site-spaceship-wreck-medium-1"] = require("___KHAOSDATA___.prototypes.data-raw.container.crash-site-spaceship-wreck-medium-1"),
  ["crash-site-spaceship-wreck-medium-2"] = require("___KHAOSDATA___.prototypes.data-raw.container.crash-site-spaceship-wreck-medium-2"),
  ["crash-site-spaceship-wreck-medium-3"] = require("___KHAOSDATA___.prototypes.data-raw.container.crash-site-spaceship-wreck-medium-3"),
  ["factorio-logo-11tiles"] = require("___KHAOSDATA___.prototypes.data-raw.container.factorio-logo-11tiles"),
  ["factorio-logo-16tiles"] = require("___KHAOSDATA___.prototypes.data-raw.container.factorio-logo-16tiles"),
  ["factorio-logo-22tiles"] = require("___KHAOSDATA___.prototypes.data-raw.container.factorio-logo-22tiles"),
  ["iron-chest"] = require("___KHAOSDATA___.prototypes.data-raw.container.iron-chest"),
  ["red-chest"] = require("___KHAOSDATA___.prototypes.data-raw.container.red-chest"),
  ["steel-chest"] = require("___KHAOSDATA___.prototypes.data-raw.container.steel-chest"),
  ["wooden-chest"] = require("___KHAOSDATA___.prototypes.data-raw.container.wooden-chest"),
}
