name: Extract

on:
  push:
    branches-ignore:
      - _template
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Extract raw data
    uses: QuingKhaos/khaosdata-raw/.github/workflows/extraction.yml@feat/extract-workflow
    secrets: inherit
    with:
      version: stable
